services:
  db:
    image: postgres
    restart: no
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
